add controller Home_page and view
lesRaidators/Les_raidators_projects pull request #39
Opened 2020-12-03 17:17 UTC by Emy78

2020-12-03 17:23 UTC, Louison-Boi reviewed
Change the routes get in resources homes

2020-12-03 17:24 UTC, Louison-Boi requested changes
Change the routes home/page

2020-12-03 19:57 UTC, Lolale commented
? que faire @Louison-Boi

2020-12-04 10:32 UTC, Emy78 reviewed
Add new changement

2020-12-04 11:17 UTC, merged